name: Open release branch

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    environment: Release
    name: Prepare final release
    if: ${{ contains(github.ref_name, 'release-v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_SECRET }}
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Exit prerelease state if needed
        run: |
          if [ -f .changeset/pre.json ]; then
            npx changeset pre exit rc
            git add .
            git commit -m "Exit release candidate"
            git push --all origin
          fi
      - name: Create PR back to main
        uses: actions/github-script@v6
        with:
          script: |
            octokit.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: github.ref_name,
              base: 'main',
              title: ${{ format('Merge {0}', github.ref_name) }}
            });
