name: Release PR

on:
  push:
    branches:
      - release-v*

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release PR or Publish
    environment: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set release title
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          BRANCH_VERSION=$(npx semver -c $(echo $BRANCH_NAME | sed "s/release-v//g"))
          PACKAGE_JSON_NEXT_PATCH=$(npx semver -i $(node --print --eval "require('./package.json').version"))
          NEXT_VERSION=$(npx semver $BRANCH_VERSION $PACKAGE_JSON_NEXT_PATCH | tail -n 1)
          echo "TITLE=Release v${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Create PR or Release to NPM
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SECRET }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          publish: npx changeset publish
          version: npm run version
          title: ${{ env.TITLE }}
          commit: ${{ env.TITLE }}
