name: Release Cycle

on:
  push:
    branches:
      - release-v*
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  start_release_candidate:
    environment: Release Cycle
    name: Start new release branch with release candidate
    if: ${{ github.ref_name == 'master' && github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # Needed so release cycle triggers when pushing
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Set changeset status location
        run: |
          CHANGESETS_STATUS_JSON=$(node --print --eval "require('path').relative(__dirname, '$RUNNER_TEMP/status.json')")
          echo "CHANGESETS_STATUS_JSON=$CHANGESETS_STATUS_JSON" >> $GITHUB_ENV
      - name: Get changeset status
        run: npx changeset status --output="$CHANGESETS_STATUS_JSON"
      - name: Get new version
        run: |
          RELEASES=$(node --print --eval "require('$CHANGESETS_STATUS_JSON').releases")
          if [ $(node --print --eval "$RELEASES.length") != 1 ]; then
            echo "::error file=$CHANGESETS_STATUS_JSON::The status doesn't contain only 1 release"
            exit 1;
          fi;
          NEW_VERSION=$(node --print --eval "($RELEASES)[0].newVersion")
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV
      - name: Open branch
        run: |
          BRANCH_SUFFIX=$(echo $NEW_VERSION | awk -F'.' '{ print $1"."$2 }')
          RELEASE_BRANCH=release-v$BRANCH_SUFFIX
          git checkout -b $RELEASE_BRANCH
      - name: Enter in prerelease state
        run: |
          npx changeset pre enter rc
          git add .
          git commit -m "Start release candidate"
          git push --all origin
  changesets_pr:
    environment: Release Cycle
    name: Changesets PR
    if: ${{ contains(github.ref_name, 'release-v') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Set release title
        env:
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          BRANCH_VERSION=$(npx semver -c $(echo $BRANCH_NAME | sed "s/release-v//g"))
          PACKAGE_JSON_NEXT_PATCH=$(npx semver -i $(node --print --eval "require('./package.json').version"))
          NEXT_VERSION=$(npx semver $BRANCH_VERSION $PACKAGE_JSON_NEXT_PATCH | tail -n 1)
          echo "TITLE=Release v${NEXT_VERSION}" >> $GITHUB_ENV
      - name: Create PR
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: npm run version
          title: ${{ env.TITLE }}
          commit: ${{ env.TITLE }}
  promote_to_final:
    environment: Release Cycle
    name: Promote to final release
    if: ${{ contains(github.ref_name, 'release-v') && github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # Needed so release cycle triggers when pushing
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Exit prerelease state if needed
        run: |
          if [ -f .changeset/pre.json ]; then
            npx changeset pre exit rc
            git add .
            git commit -m "Exit release candidate"
            git push --all origin
          fi
      - name: Create PR back to main
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ github.ref_name }}',
              base: 'main',
              title: '${{ format('Merge {0} branch', github.ref_name) }}'
            });
  publish:
    environment: npm
    name: Promote to final release
    if: ${{ contains(github.ref_name, 'release-v') && github.event_name == 'push' && steps.changesets.outputs.published == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }} # Needed so release cycle triggers when pushing
      - name: Set up environment
        uses: ./.github/actions/setup
      - run: bash scripts/git-user-config.sh
      - name: Tag
        run: npx changeset tag
      - name: Publish to npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
      - name: Upload tags
        run: git push --tags
